//! SFW / NSFW stage tag presets.

pub const TAGS_SFW: &[&str] = &[
    "Behind", "Facing", "Holding", "Hugging", "Kissing", "Kneeling", "Loving", "Lying", "Magic",
    "Sitting", "Spooning", "Standing",
];

pub const TAGS_NSFW: &[&str] = &[
    "69",
    "Anal",
    "Asphyxiation",
    "Blowjob",
    "Boobjob",
    "Breast Sucking",
    "Buttjob",
    "Cowgirl",
    "Cunnilingus",
    "Deepthroat",
    "Doggy",
    "Dominant",
    "Double Penetration",
    "Face Sitting",
    "Facial",
    "Feet",
    "Fingering",
    "Fisting",
    "Footjob",
    "Forced",
    "Gore",
    "Grinding",
    "Handjob",
    "Humiliation",
    "Lead In",
    "Lotus Position",
    "Masturbation",
    "Missionary",
    "Oral",
    "Oviposition",
    "Penetration",
    "Prone Bone",
    "Reverse Cowgirl",
    "Reverse Spitroast",
    "Rimming",
    "Ryona",
    "Spanking",
    "Spitroast",
    "Teasing",
    "Toys",
    "Tribadism",
    "Triple Penetration",
    "Vaginal",
];

pub const SLAL_SOUNDS: &[&str] = &["", "Squishing", "Sucking", "SexMix", "none", "NoSound"];
